### ISSUE TITLE
PLUGIN ERROR

### ISSUE THREAD

**Issue by uRyanxD** [bob7l/Clearlag-Languages#21]
[21:42:37 WARN]: [ClearLag] Task #25 for ClearLag v3.2.0 generated an exception
java.lang.NullPointerException: null
        at me.minebuilders.clearlag.tasks.ClearTask.run(ClearTask.java:44) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-434]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-434]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1293) ~[patched_1.16.5.jar:git-Paper-434]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-434]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.5.jar:git-Paper-434]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.5.jar:git-Paper-434]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-434]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by bob7l** [comment]
That means your warning messages failed to load. Check out your error logs for exceptions while the server was turning on and run  your config through a YAML checker website.
