### ISSUE TITLE
Could not pass event ChunkLoadEvent to ClearLag v3.2.0

### ISSUE THREAD

**Issue by twixi** [bob7l/Clearlag-Languages#35]
`[22:48:16] [Server thread/ERROR]: Could not pass event ChunkLoadEvent to ClearLag v3.2.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:59) [ChunkIOProvider.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15) [ChunkIOProvider.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189) [AsynchronousExecutor$Task.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354) [AsynchronousExecutor.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30) [ChunkIOExecutor.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:885) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Entity.getCustomName()Ljava/lang/String;
	at me.minebuilders.clearlag.entities.attributes.EntityHasNameAttribute.containsData(EntityHasNameAttribute.java:12) ~[?:?]
	at me.minebuilders.clearlag.entities.EntityMap.getValue(EntityMap.java:41) ~[?:?]
	at me.minebuilders.clearlag.listeners.ChunkPerEntityLimiterListener.onChunkLoad(ChunkPerEntityLimiterListener.java:32) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]
	... 13 more`

**Comment by bob7l** [comment]
You need to use the legacy version on bukkit.dev.
